group
<?php if( $this->group->getUsers() ) foreach( $this->group->getUsers() as $user): ?>
	<a style="width: 200px; height: 120px; padding-top: 80px; margin-right: 10px; margin-bottom: 10px; margin-top: 10px; background: #2586d0; color: white; display: inline-block; text-align: center;" 
	   href="<?php echo $this->url( array( 'object' => $user->getId() ), 'user' ); ?>" >
		<?php echo $user->getName(); ?> <?php echo $user->getSurname(); ?>
	</a>
<?php endforeach; ?>

	
