<?php if( $this->groups ) foreach( $this->groups as $group ): ?>
	<a style="width: 200px; height: 120px; padding-top: 80px; margin-right: 10px; margin-bottom: 10px; margin-top: 10px; background: #2586d0; color: white; display: inline-block; text-align: center;" 
	   href="<?php echo $this->url( array( 'object' => $this->user->getId(), 'group' => $group->id ), 'user-group' ); ?>" >
		<?php echo $group->getName(); ?>
	</a>
<?php endforeach; ?>

<a style="width: 200px; height: 120px; padding-top: 80px; margin-right: 10px; margin-bottom: 10px; margin-top: 10px; background: #91BE3F; color: white; display: inline-block; text-align: center;" 
	href="<?php echo $this->url( array(), 'user-addgroup' ); ?>" >
	 Dodaj grupe
 </a>