<script type="text/javascript" charset="UTF-8">

	
</script>

<?php echo $this->entity->getImageMenu()->render(); ?>

<?php foreach( $this->albums as $album ): ?>
	<a style="width: 200px;
				height: 120px;
				padding-top: 80px;
				margin-right: 10px;
				margin-bottom: 10px;
				margin-top: 10px;
				background: #2586d0;
				color: white;
				display: inline-block;
				text-align: center;" 
		href="<?php echo $this->url( array( 'album' => $album->getId() ), 'album' ); ?>" >
			<?php echo $album->getTitle(); ?>
	</a>
<?php endforeach; ?>

<?php if( $this->entity->isAllowed( "addAlbum" ) ): ?>
<a style="width: 200px;
    height: 120px;
    padding-top: 80px;
    margin-right: 10px;
    margin-bottom: 10px;
    margin-top: 10px;
    background: #91BE3F;
    color: white;
    display: inline-block;
    text-align: center;" 
    href="<?php echo $this->baseUrl( 'image/image/addalbum' ); ?>" >
        Dodaj album
</a>
<?php endif; ?>