<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->jQuery(); ?>	
		<?php $this->headLink()->appendStylesheet( $this->baseUrl().'/application/layouts/scripts/css/standard.css'); ?>
		<?php $this->headLink()->appendStylesheet( $this->baseUrl().'/application/layouts/scripts/css/container.css'); ?>
		<?php $this->headScript()->appendFile( $this->baseUrl().'/application/js/html5uploader/html5uploader.js'); ?>
		<?php $this->headScript()->appendFile( $this->baseUrl().'/application/js/html5uploader/dropZone.js'); ?>
		<?php //$this->headLink()->appendStylesheet( $this->baseUrl().'/../application/js/makiForm/css/makiForm.css'); ?>
		<?php //$this->headLink()->appendStylesheet( $this->baseUrl().'/../application/js/timePicker/css/timePicker.css'); ?>
		
		<?php //$this->headLink()->appendStylesheet('/makicms/application/js/ui/css/ui-lightness/jquery-ui-1.8.23.custom.css') ?>
		<?php $this->headScript()->appendFile( $this->baseUrl().'/application/js/object.js' ); ?>
		<?php $this->headScript()->appendFile( $this->baseUrl().'/application/js/buttonResize.js' ); ?>
		<?php $this->headScript()->appendFile( $this->baseUrl().'/application/js/images.js' ); ?>
		<?php $this->headScript()->appendFile( $this->baseUrl().'/application/js/objectTask.js' ); ?>
		<?php //$this->headScript()->appendFile( $this->baseUrl().'/../application/js/ui/js/jquery-ui-1.8.23.custom.min.js'); ?>
		<!--
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/jquery-ui.min.js"></script>
		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/smoothness/jquery-ui.css" type="text/css" media="screen">
		-->
		<?php echo $this->headLink(); ?>
		<?php echo $this->headScript(); ?>
		<style type="text/css">
		/* <![CDATA[ */
		ul.addToGroupList{
			display: none;
			position: absolute;
			background: white;
			left: 0;
			top: 2rem;
		}
		li.addToGroupButton:hover ul.addToGroupList{
			display: inline-block;
		}
		li.addToGroupButton{
			position: relative;
		}
		/* ]]> */
		</style>
		<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500&subset=latin,cyrillic-ext' rel='stylesheet' type='text/css'>
	</head>
	<body>
		<div id="menu" >
			<?php echo $this->menu()->render(); ?>
		</div>
		<div id="content" >
			<?php echo $this->layout()->content; ?>
		</div>
	</body>
</html>