<?php echo $this->action( 'information', 'information', 'entity', array( 'entity' => $this->entity->getId(), 'no_entity_template' => 1  ) ); ?>

<?php if( $this->entity->getObjectClass() == 'Moondee_Entity_User' ): ?>
	<?php echo $this->action( 'description', 'description', 'entity', array( 'entity' => $this->entity->getId(), 'no_entity_template' => 1  ) ); ?>
<?php else: ?>
	<?php echo $this->action( 'best-description', 'description', 'entity', array( 'entity' => $this->entity->getId(), 'no_entity_template' => 1  ) ); ?>
<?php endif; ?>

