<p><?= $this->entity->getName(); ?> <?= $this->entity->getSurname(); ?></p>
<div class="information_list" >
	<div class="row" >
		<div class="left" >
			<p>email</p>
		</div>
		<div class="right" >
			<?php foreach( $this->entity->getEmails() as $email ): ?>
				<p><?= $email; ?></p>
			<?php endforeach; ?>
		</div>
	</div>
	<div class="row" >
		<div class="left" >
			<p>email</p>
		</div>
		<div class="right" >
			<?php foreach( $this->entity->getEmails() as $email ): ?>
				<p><?= $email; ?></p>
			<?php endforeach; ?>
		</div>
	</div>
	<div class="row" >
		<div class="left" >
			<p>email</p>
		</div>
		<div class="right" >
			<?php foreach( $this->entity->getEmails() as $email ): ?>
				<p><?= $email; ?></p>
			<?php endforeach; ?>
		</div>
	</div>
</div>
<p>

</p>
