<div id="screenSizeContainer">
			
</div>
<div id="objectBackgroundFoto" style="background-image: url(/../moondeebox/images/flaka-image.jpg); ">
	<div id="objectMenu" >
		<div class="avatarBackground top" ></div>
		<div class="avatarBackground bottom" ></div>

		<div class="avatarBox" >
                    <img src="<?php echo $this->baseUrl(); ?>/images/goya.jpg" class="avatar" align="middle" >
		</div>
		
		<?php echo $this->entity->getRealObject()->getTaskMenu()->render() ; ?>
		
		<?php echo $this->entity->getRealObject()->getMenu()->render() ; ?>
	
	</div>
</div>
<div id="objectContent">
	<?php echo $this->render( $this->entity_script ); ?>
</div>		